theme: jekyll-theme-cayman

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - colorscheme.md
  - colorpicker.md
  - gridview.md
  - flutterissues.md
