theme: jekyll-theme-cayman
title: RydMike's homepage
description: Fluttering with RydMike, public Flutter projects and articles.
url: "https://rydmike.com"

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - 404.md
  - flexfold.md
  - colorscheme.md
  - colorpicker.md
  - gridview.md
  - issues.md
  - talo.md
  - blog.md
  - blog_m3_talk.md
  - blog_flutter_linting.md
  - blog_cliprect_boxshadow.md
  - blog_sliver_padding.md
  - blog_layout_and_theming.md
  - blog_theming_guide.md
  - blog_roads_to_theme_data.md
  - blog_vikings_2022_talk.md
