theme: jekyll-theme-cayman
title: RydMike Fluttering
description: Public Flutter projects and articles
url: "https://rydmike.com"

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-relative-links
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  
readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

relative_links:
  enabled: true
  collections: true

optional_front_matter:
  enabled: true
  remove_originals: true

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false  

include:
  - README.md
  - 404.md
  - flexfold.md
  - colorscheme.md
  - colorpicker.md
  - gridview.md
  - issues.md
  - talo.md
  - blog.md
  - blog_m3_talk.md
  - blog_flutter_linting.md
  - blog_cliprect_boxshadow.md
  - blog_sliver_padding.md
  - blog_layout_and_theming.md
  - blog_theming_guide.md
  - blog_theme_demo.md
  - blog_roads_to_theme_data.md
  - blog_vikings_2022_talk.md
  - _posts
