theme: jekyll-theme-cayman

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - flexfold.md
  - colorscheme.md
  - colorpicker.md
  - gridview.md
  - issues.md
  - talo.md
  - blog.md
  - blog_flutter_linting.md
  - blog_cliprect_boxshadow.md
  - blog_sliver_padding.md
  - blog_layout_and_theming.md
  - blog_theming_guide.md
  - blog_roads_to_theme_data.md
